[package]
name = "pg_tool"
version = "0.1.0"
authors = ["Paul Colusso <paulcolusso@gmail.com>"]
edition = "2018"

[dependencies]
postgres = "0.15.2"
clap = "2.33.0"
indicatif = "0.11.0"
serde = { version = "1.0.91", features = ["derive"] }
serde_yaml = "0.8.9"
simple-error = "0.1.13"
